<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del tipo de contrato laboral</legend>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('tipo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('plantilla')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('plantilla')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-file"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR TIPO CONTRATO LABORAL"><i class="fas fa-save"></i> Registrar TCL</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idTipoContratoLaboral')->setValue(0));
echo $this->form()->closeTag();
?>