<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos</legend>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('mentor')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('mentor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idFacultad')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idFacultad')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idGVRI')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idGVRI')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idGSIVRI')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idGSIVRI')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('codColombia')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('codColombia')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('correo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('correo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('imagen')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('imagen')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-pdf-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('enlaceGruplac')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('enlaceGruplac')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-pdf-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('enlaceSivri')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('enlaceSivri')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-pdf-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('detalle')) ?>
                    <div class="input-group">
                        <div class="editor-container">
                            <?= $this->formElement($form->get('detalle')) ?>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button id="registrarHP" type="submit" class="btn btn-success" title="REGISTRAR GRUPO"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idGI')->setValue(0));
echo $this->form()->closeTag();
?>
<!-- <script>
    $(document).ready(function() {
        let editorInstance;

        ClassicEditor
            .create(document.querySelector('#detalle'), {
                toolbar: [
                    'heading', '|',
                    'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', '|',
                    'undo', 'redo', 'codeBlock', 'imageUpload', 'insertTable', 'mediaEmbed', 'htmlEmbed'
                ],
                heading: {
                    options: [{
                            model: 'paragraph',
                            title: 'Paragraph',
                            class: 'ck-heading_paragraph'
                        },
                        {
                            model: 'heading1',
                            view: 'h1',
                            title: 'Heading 1',
                            class: 'ck-heading_heading1'
                        },
                        {
                            model: 'heading2',
                            view: 'h2',
                            title: 'Heading 2',
                            class: 'ck-heading_heading2'
                        },
                        {
                            model: 'heading3',
                            view: 'h3',
                            title: 'Heading 3',
                            class: 'ck-heading_heading3'
                        }
                    ]
                }
            })
            .then(editor => {
                editorInstance = editor;
            })
            .catch(error => {
                console.error(error);
            });

        $('#registrarHP').on('click', function() {
            if (editorInstance) {
                $('#detalle').val(editorInstance.getData());
            }
            $('#formGrupo').submit();
        });

        $('#formGrupo').on('submit', function(event) {
            event.preventDefault();
            // Realiza tu lógica de envío, por ejemplo, usando AJAX
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(response) {
                    console.log('Form submitted successfully');
                    // Cierra el modal después de un envío exitoso
                    //$('#modalFormulario').modal('hide');
                },
                error: function(error) {
                    console.error('Error submitting form', error);
                }
            });
        });
    });
</script> -->
<script>
    var editor;
    ClassicEditor
        .create(document.querySelector('#detalle'))
        .then(newEditor => {
            editor = newEditor;
        })
        .catch(error => {
            console.error(error);
        });
</script>