<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del evento</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre_programa')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre_programa')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('detalle_programa')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('detalle_programa')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('segmento')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('segmento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-sun-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('hora_inicio')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('hora_inicio')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-clock-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('hora_fin')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('hora_fin')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-clock-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('color_programa')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('color_programa')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-paint-brush"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('imagen')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('imagen')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-image-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('dias')) ?>
                    <div class="d-flex justify-content-between">
                        <?= $this->formElement($form->get('dias')) ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" titulo="REGISTRAR PROGRAMA"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idPrograma')->setValue(0));
echo $this->form()->closeTag();
?>