<?php

use Laminas\Mvc\Application;

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

?>
<i class="fa fa-exclamation-triangle fa-5x animated wobble" style="color: red;"></i>
<h1 class="animated bounceInRight">Se produjo un error <b style="color: #000000;">404</b></h1>
<h2><?= $this->message ?></h2>

<?php if (!empty($this->reason)) :
    switch ($this->reason) {
        case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
            $reasonMessage = 'El controlador solicitado no pudo enviar la solicitud.';
            break;
        case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
            $reasonMessage = 'El middleware solicitado no pudo enviar la solicitud.';
            break;
        case Application::ERROR_CONTROLLER_NOT_FOUND:
            $reasonMessage = 'El controlador solicitado no se pudo asignar a una clase de controlador existente.';
            break;
        case Application::ERROR_CONTROLLER_INVALID:
            $reasonMessage = 'El controlador solicitado no se podía enviar.';
            break;
        case Application::ERROR_ROUTER_NO_MATCH:
            $reasonMessage = 'La URL solicitada no pudo coincidir con la ruta.';
            break;
        default:
            $reasonMessage = 'No podemos determinar en este momento por qué se generó un 404.';
            break;
    }
?>
    <p><?= $reasonMessage ?></p>
<?php endif ?>

<?php if (!empty($this->controller)) : ?>
    <dl>
        <dt>Controller:</dt>
        <dd>
            <?= $this->escapeHtml($this->controller) ?>
            <?php
            if (!empty($this->controller_class) && $this->controller_class != $this->controller) {
                printf('(resolves to %s)', $this->escapeHtml($this->controller_class));
            }
            ?>
        </dd>
    </dl>
<?php endif ?>

<?php if (!empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception) && $this->exception instanceof \Throwable) : ?>
        <hr />

        <h2>Additional information:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
            <hr />

            <h2>Previous exceptions:</h2>
            <ul class="list-unstyled">
                <?php $icount = 0 ?>
                <?php while ($ex) : ?>
                    <li>
                        <h3><?= get_class($ex) ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $ex = $ex->getPrevious();
                    if (++$icount >= 50) {
                        echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                        break;
                    }
                    ?>
                <?php endwhile ?>
            </ul>
        <?php endif ?>
    <?php else : ?>
        <h3>No hay excepción disponible</h3>
        <h1 class="animated bounce hvr-buzz estilologo"><b><i><img src="<?= $this->basePath('img/logo.png') ?>" /> GestorPortal</i></b></h1>
    <?php endif ?>
<?php endif ?>