<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del usuario</legend>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idEmpleadoCliente')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idEmpleadoCliente')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-users"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idRol')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idRol')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-universal-access"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('usuario')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('usuario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user-tie"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('login')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('login')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-user-secret"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('password')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('password')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-unlock-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('passwordseguro')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('passwordseguro')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="position: absolute;right:3px;top:4px;" onclick="hideshow()">
                                <i id="slash" class="fa fa-eye-slash"></i>
                                <i id="eye" class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn btn-info btn-sm" onclick="generarContrasenia()">Generar contraseña</button>
                    </div>
                </div>
            </div>
            <small id="passwordHelp" class="form-text text-muted">
                La contraseña debe tener entre 12 y 25 caracteres, incluyendo al menos una mayúscula, una minúscula, un número y un carácter especial.
            </small>
            <div id="error" class="mt-3"></div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR USUARIO"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idUsuario')->setValue(0));
echo $this->form()->closeTag();
?>

<script>
    function hideshow() {
        var password = document.getElementById("password");
        var passwordseguro = document.getElementById("passwordseguro");
        var slash = document.getElementById("slash");
        var eye = document.getElementById("eye");

        if (password.type === 'password' || passwordseguro.type === 'password') {
            password.type = "text";
            passwordseguro.type = "text";
            slash.style.display = "block";
            eye.style.display = "none";
        } else {
            password.type = "password";
            passwordseguro.type = "password";
            slash.style.display = "none";
            eye.style.display = "block";
        }

    }
</script>