<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'GestorPortal';
    switch ($tipo) {
        case 'success':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "new PNotify({
            title: '$titulo',
            text: '$mensaje',
            type: '$tipoToastr',
            styling: 'bootstrap3'
        });";
    }
}
//------------------------------------------------------------------------------

$title = 'Gestor de Formularios';
$this->headTitle($title);
$this->headLink();
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#myTable").DataTable({
                    responsive: true,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('js/sistema/formulario.js'))
    ->prependFile($this->basePath('js/jquery.blockUI.js'));

?>
<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_title">
            <h2><span data-feather="file-text"></span> Gestor de Formulario</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <ul class="nav nav-tabs bar_tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('formularios/userform', array('controller' => 'userform', 'action' => 'index')) ?>" title="TURNOS">Gestor de Formularios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('formularios/userform', array('controller' => 'userform', 'action' => 'indexDependencia')) ?>" title="REPORTES">Dependencias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="<?= $this->url('formularios/userform', array('controller' => 'userform', 'action' => 'userDep')) ?>" title="Usuarios Dependencias">Usuarios - Dependencias</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="card-box table-responsive">
                    <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
                        <thead class="thead-dark">
                            <tr>
                                <!-- <th data-toggle="tooltip" title="ID"><i class="fa fa-key"></i></th>
                                <th data-toggle="tooltip" title="OPCIONES"><i class="fa fa-cog fa-spin fa-lg"></i></th> -->
                                <th>DEPENDENCIA</th>
                                <th>CORREO</th>
                                <th>FORMULARIO</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->userDepAll as $userDep) {
                                echo '<tr>';
                                /*   echo '<td>' . $userDep['idform_dependencia'] . '</td>';
                                echo '<td>';
                                echo '<a data-toggle="tooltip" href="" onclick="verDetalle(' . $userDep['idform_dependencia'] . '); return false;" title="VER VENTA"><i class="fa fa-eye"></i></a>';
                                echo '&nbsp;&nbsp;';
                                echo '</td>'; */
                                echo '<td>' . $userDep['nombre'] . '</td>';
                                echo '<td>' . $userDep['correo'] . '</td>';
                                echo '<td>' . $userDep['dependencia'] . '</td>';
                                echo '</tr>';
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="msgBloqueo" style="display: none;">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i> SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>