<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <div class="d-flex justify-content-between align-items-center w-100">
                <strong class="text-gray-dark">Se listan los formularios registados al correo actual</strong>
                <a type="button" class="btn btn-primary" href="javascript:addDep(<?= $this->idform_user ?>);" title="REGISTRAR"><i class="fa fa-plus-circle fa-2x"></i></a>
            </div>
            <table id="myTable3" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
                <thead class="thead-dark">
                    <tr>
                        <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                        <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
                        <th scope="col"><i class="fas fa-id-card"></i> DEPENDENCIA</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->fetchAll as $userForm) {
                        echo '<tr>';
                        echo '<td>' . $userForm['idform_dependencia'] . '</td>';
                        echo '<td>';
                        echo '<a href="javascript:eliminarUserForm(' . $userForm['idform_dependencia'] . ',' . $this->idform_user . ')" return false;" title="ELIMINAR"><i style ="color:red" class="fa fa-trash"></i></a>';
                        echo '</td>';
                        echo '<td>' . $userForm['dependencia'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $("#myTable3").DataTable({
        responsive: true,
        "iDisplayLength": 25,
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
            "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
            "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
            "sInfoEmpty": "Mostrando 0 A 0 registros",
            "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
            "sLoadingRecords": "CARGANDO...",
            "sProcessing": "EN PROCESO...",
            "sSearch": "Buscar:",
            "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
            "oPaginate": {
                "sFirst": "Inicio",
                "sLast": "Fin",
                "sNext": "Siguiente",
                "sPrevious": "Anterior"
            }
        },
        "aaSorting": [
            [0, "desc"]
        ]
    });
</script>