<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'GestorPortal';
    switch ($tipo) {
        case 'success':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "new PNotify({
            title: '$titulo',
            text: '$mensaje',
            type: '$tipoToastr',
            styling: 'bootstrap3'
        });";
    }
}
//------------------------------------------------------------------------------

$title = 'PFI';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {                
                $("#myTable").DataTable({
                    responsive: true,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });                
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('js/sistema/pfi.js'))
    ->prependFile($this->basePath('js/ckeditor.js'))
    ->prependFile($this->basePath('js/jquery.blockUI.js'))
    ->prependFile($this->basePath('js/select2.min.js'))
    ->prependFile($this->basePath('js/select2.es.js'));

?>
<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <div class="d-flex justify-content-between align-items-center w-100">
                            <strong class="text-gray-dark">Se listan los formularios registrados en el sistema</strong>
                            <a type="button" class="btn btn-primary" href="javascript:verRegistrar();" title="REGISTRAR"><span data-feather="file-plus"></span></a>
                        </div>

                        <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
                            <thead class="thead-dark">
                                <tr>
                                    <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                                    <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
                                    <th scope="col"><i class="fas fa-id-card"></i> NOMBRE</th>
                                    <th scope="col"><i class="fas fa-sort-numeric-asc"></i> CUPO</th>
                                    <th scope="col"><i class="fas fa-calendar-check-o"></i> Fecha Inicio</th>
                                    <th scope="col"><i class="fas fa-calendar-times-o"></i> Fecha FIN</th>
                                    <th scope="col"><i class="fas fa-clock-o"></i> HORA LÍMITE</th>
                                    <th scope="col"><i class="fas fa-calendar"></i> REGISTRADO</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($this->fetchAll as $pfi) {
                                    $color = '';
                                    $botonActivar = '';
                                    $botonDesactivar = '';
                                    if ($pfi['activo'] == '1') {
                                        $color = '#AFA';
                                        $botonActivar = 'hidden';
                                        $botonDesactivar = '';
                                    } else {
                                        $color = '#FAA';
                                        $botonActivar = '';
                                        $botonDesactivar = 'hidden';
                                    }
                                    echo '<tr>';
                                    echo '<td>' . $pfi['id_config']  . '</td>';
                                    echo '<td>';
                                    echo '<a href="javascript:verDetalle(' . $pfi['id_config'] . ')" title="VER"><i class="fas fa-eye"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="javascript:verEditar(' . $pfi['id_config']  . ')" title="EDITAR"><i class="fa fa-edit"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="javascript:verActivar(' . $pfi['id_config'] . ')" title="ACTIVAR" ' . $botonActivar . '><i class="fa fa-check-circle" style="color:green;"></i></a>';
                                    echo '<a href="javascript:verDesactivar(' . $pfi['id_config'] . ')" title="DESACTIVAR" ' . $botonDesactivar . '><i class="fa fa-ban" style="color:orange;"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="javascript:verEliminar(' . $pfi['id_config'] . ')" title="ELIMINAR"><i class="fa fa-trash" style="color:red;"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '</td>';
                                    echo '<td>' . substr($pfi['nombre_formulario'], 0, 125)  . '</td>';
                                    echo '<td>' . $pfi['cupo_maximo']  . '</td>';
                                    echo '<td>' . $pfi['fecha_inicio']  . '</td>';
                                    echo '<td>' . $pfi['fecha_fin']  . '</td>';
                                    echo '<td>' . $pfi['hora_limite_diaria'] . '</td>';
                                    echo '<td style="background-color: ' . $color . ';">' . $pfi['created_at']  . '</td>';
                                    echo '</tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i> SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>