<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del evento</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre_formulario')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre_formulario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('slug')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('slug')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('cupo_maximo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('cupo_maximo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-sort-numeric-asc"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('fecha_inicio')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fecha_inicio')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-check-o"></i>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('fecha_fin')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fecha_fin')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-times-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('hora_limite_diaria')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('hora_limite_diaria')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-clock-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('instrucciones')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('instrucciones')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR FORMULARIO"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('id_config')->setValue(0));
echo $this->form()->closeTag();
?>