<?php
$form->prepare();
$form->get('ruta_archivo')->setAttribute('readonly', true);
$form->get('ruta_archivo')->setAttribute('required', false);
$form->get('ruta_archivo')->setAttribute('type', 'text');
$form->get('tipo_documento')->setAttribute('readonly', true);
$form->get('tipo_documento')->setAttribute('required', false);
$form->get('tipo_documento')->setAttribute('type', 'text');
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('titulo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('titulo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('fecha_publicacion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fecha_publicacion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('tipo_documento')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipo_documento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-file-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('ruta_archivo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('ruta_archivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-file-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('activo')) ?>
                    <div class="form-check">
                        <?= $this->formCheckbox($form->get('activo')) ?>
                        <label class="form-check-label" for="activo">Activar</label>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="id"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('id')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="creado_por">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('creado_por')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="actualizado_por">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('actualizado_por')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="creado_el">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('creado_el')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="actualizado_el">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('actualizado_el')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-danger" title="ELIMINAR DOCUMENTO"><i class="fa fa-trash"></i> Eliminar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>