<?php
$form->prepare();
$form->get('archivo')->setAttribute('readonly', true);
$form->get('archivo')->setAttribute('type', 'text');
$form->get('tipoDocumento')->setAttribute('readonly', true);
$form->get('tipoDocumento')->setAttribute('type', 'text');
$form->get('idEmitido')->setAttribute('readonly', true);
$form->get('idEmitido')->setAttribute('type', 'text');
echo $this->form()->openTag($form);
?>
<div class="modal-body">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del empleado</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('publicacion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('publicacion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('tipoDocumento')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipoDocumento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('archivo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('archivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group">
                                <button type="button" onclick="actualizarArchivo()" class="btn btn-primary" title="ACTUALIZAR EL ARCHIVO"><i class="fa fa-upload"></i></button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-2 col-sm-12">
                    <label class="control-label" for="idCPResultados"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idCPResultados')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-2 col-sm-12">
                    <?= $this->formLabel($form->get('idEmitido')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idEmitido')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('modificadopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahoramod">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahoramod')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-danger" title="ELIMINAR EMPLEADO"><i class="fa fa-trash"></i> Eliminar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>