<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos</legend>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('nombre_documento')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre_documento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('documento')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('documento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-file-pdf"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <table class="table table-sm table-dark">
            <thead>
                <tr>
                    <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                    <th scope="col">DOCUMENTO</th>
                    <th scope="col">REGISTRADO</th>
                    <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
                </tr>
            </thead>
            <tbody>
                <?php
                if (empty($this->orriDocumentos)) {
                    echo '<tr><th><i class="fa fa-exclamation-triangle" style="color: yellow;"></i></th><th>ORII NO TIENE REGISTRADOS DOCUMENTOS</th><th></th><th></th></tr>';
                } else {
                    foreach ($this->orriDocumentos as $qr) {
                        echo '<tr>';
                        echo '<th scope="row">' . $qr['id_documentos_orii'] . '</th>';
                        echo  '<th>' . $qr['nombre_documento'] . '</th>';
                        echo  '<th>' . $qr['fechahorareg_documento'] . '</th>';
                        echo  '<th>';
                        echo '<a href="./../orii/verArchivo/' . $qr['id_documentos_orii']  . '" target="_blank" title="' . $qr['nombre_documento'] . '"><i class="fa fa-file-pdf-o"></i></a>';
                        echo '&nbsp;&nbsp;';
                        echo '<a href="javascript:eliminarDoc(' . $qr['id_documentos_orii']  . ')" title="ELIMINAR"><i class="fa fa-trash" style="color:red;"></i></a>';
                        echo  '</th>';
                        echo '</tr>';
                    }
                }
                ?>
            </tbody>
        </table>
        <fieldset>
            <legend>Informacion de ORII</legend>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label">Nombre de Convenio</label>
                    <div class="input-group">
                        <input type='text' value="<?= $this->oriiDetalle['nombre_convenio'] ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label">Número de Convenio</label>
                    <div class="input-group">
                        <input type='text' value="<?= $this->oriiDetalle['numero_convenio'] ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="idOrii"><i class="fas fa-key"></i> ID ORII</label>
                    <div class="input-group">
                        <input type='text' id="idOrii" name="idOrii" value="<?= $this->oriiDetalle['idOrii'] ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label">Publicación</label>
                    <div class="input-group">
                        <input type='text' value="<?= $this->oriiDetalle['publicacion'] ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="modal-footer" style="padding: 20px">
            <button type="submit" class="btn btn-success" title="REGISTRAR DOCUMENTO"><i class="fas fa-save"></i> Registrar Documento</button>
            <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
        </div>
    </div>
</div>
<?php
echo $this->formHidden($form->get('id_documentos_orii')->setValue(0));
echo $this->form()->closeTag();
?>