<div class="modal-body">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Informacion del Plugin</legend>
            <div class="form-row">
                <div class="form-group col-md-12 col-sm-12">
                    <label class="control-label" for="nombre_modulo">Nombre</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['nombre_modulo']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <label class="control-label" for="ruta_archivo">Ruta del Archivo</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['ruta_archivo']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-briefcase"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <label class="control-label" for="descripcion">Comentario</label>
                    <div class="input-group">
                        <textarea class="form-control" id="descripcion" rows="3" readonly><?php echo $this->form['descripcion']; ?></textarea>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-comment-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="id"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['id']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="activo">Activo </label>
                    <div class="input-group">
                        <input type='text' id="activo " name="activo" value="<?php echo $this->form['activo']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <input type='text' id="registradopor" name="registradopor" value="<?php echo $this->form['registradopor']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <input type='text' id="modificadopor" name="modificadopor" value="<?php echo $this->form['modificadopor']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fecha_creacion">Registrado</label>
                    <div class="input-group">
                        <input type='text' id="fecha_creacion" name="fecha_creacion" value="<?php echo $this->form['fecha_creacion']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fecha_actualizacion">Modificado</label>
                    <div class="input-group">
                        <input type='text' id="fecha_actualizacion" name="fecha_actualizacion" value="<?php echo $this->form['fecha_actualizacion']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>