<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Cambio de Contraseña</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('passwordactual')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('passwordactual')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="position: absolute;right:3px;top:4px;" onclick="hideshow()">
                                <i id="slash" class="fa fa-eye-slash"></i>
                                <i id="eye" class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('password')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('password')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="position: absolute;right:3px;top:4px;" onclick="hideshow()">
                                <i id="slash2" class="fa fa-eye-slash" style="display: none;"></i>
                                <i id="eye2" class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                    <small id="passwordHelp" class="form-text text-muted">
                        La contraseña debe tener entre 12 y 25 caracteres, incluyendo al menos una mayúscula, una minúscula, un número y un carácter especial.
                    </small>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('passwordConfirm')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('passwordConfirm')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="position: absolute;right:3px;top:4px;" onclick="hideshow()">
                                <i id="slash3" class="fa fa-eye-slash" style="display: none;"></i>
                                <i id="eye3" class="fa fa-eye"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div id="error" class="mt-3"></div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="CAMBIAR CONTRASEÑA"><i class="fas fa-save"></i> Cambiar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>

<script>
    function hideshow() {
        var passwordactual = document.getElementById("passwordactual");
        var password = document.getElementById("password");
        var passwordConfirm = document.getElementById("passwordConfirm");
        var slash = document.getElementById("slash");
        var eye = document.getElementById("eye");
        var slash2 = document.getElementById("slash2");
        var eye2 = document.getElementById("eye2");
        var slash3 = document.getElementById("slash3");
        var eye3 = document.getElementById("eye3");

        if (passwordactual.type === 'password' || password.type === 'password' || passwordConfirm.type === 'password') {
            passwordactual.type = "text";
            password.type = "text";
            passwordConfirm.type = "text";
            slash.style.display = "block";
            eye.style.display = "none";
            slash2.style.display = "block";
            eye2.style.display = "none";
            slash3.style.display = "block";
            eye3.style.display = "none";
        } else {
            passwordactual.type = "password";
            password.type = "password";
            passwordConfirm.type = "password";
            slash.style.display = "none";
            eye.style.display = "block";
            slash2.style.display = "none";
            eye2.style.display = "block";
            slash3.style.display = "none";
            eye3.style.display = "block";
        }

    }
    $(document).ready(function() {
        // Función para manejar el evento de pegar en el campo de contraseña
        $('#password').on('paste', function(e) {
            e.preventDefault(); // Evitar la acción de pegado
            Swal.fire('No se puede pegar texto en este campo.', 'GestorPortal', 'error');
        });
        $('#passwordConfirm').on('paste', function(e) {
            e.preventDefault(); // Evitar la acción de pegado
            Swal.fire('No se puede pegar texto en este campo.', 'GestorPortal', 'error');
        });
    });
</script>