<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos</legend>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('cargo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('cargo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-briefcase"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('telefono')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('telefono')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-phone-square"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('correo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('correo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-envelope"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('direccion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('direccion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-map-marker"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('unidad')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('unidad')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-building"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('idDependencia')) ?>
                    <div class="input-group" id="divDep">
                        <?= $this->formElement($form->get('idDependencia')) ?>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('asistente')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('asistente')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-users"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('cargoAsistente')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('cargoAsistente')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-briefcase"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR USUARIO"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idDI')->setValue(0));
echo $this->form()->closeTag();
?>

<script>
    $.fn.select2.defaults.set('language', 'es');
    $("#idDependencia").select2({
        width: '100%',
        dropdownParent: $('#divDep'),
    });
</script>