<div class="card-box table-responsive">
    <div class="d-flex justify-content-between align-items-center w-100">
        <strong class="text-gray-dark">Se listan los archivos registrados en el sistema</strong>
    </div>
    <table id="myTable2" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
        <thead class="thead-dark">
            <tr>
                <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                <th scope="col"><i class="fas fa-id-card"></i> NOMBRE</th>
                <th scope="col"><i class="fas fa-id-card"></i> TIPO</th>
                <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->lvmen as $qs) {
                echo '<tr>';
                echo '<td>' . $qs['idLvmen']  . '</td>';
                echo '<td>' . substr($qs['nombre'], 0, 95)  . '</td>';
                echo '<td>' . $qs['tipoDocumento']  . '</td>';
                echo '<td>';
                echo '<a href="javascript:selectLvmen(' . $qs['idLvmen'] . ',\'' . $qs['nombre'] . '\')" title="SELECCIONAR DOCUMENTO"><i class="fa fa-check-square"></i></a>';
                echo '&nbsp;&nbsp;';
                echo '</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>
</div>

<script>
    $("#myTable2").DataTable({
        responsive: true,
        iDisplayLength: 25,
        sPaginationType: "full_numbers",
        oLanguage: {
            sLengthMenu: "Mostrar: _MENU_ registros por pagina",
            sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
            sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
            sInfoEmpty: "Mostrando 0 A 0 registros",
            sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
            sLoadingRecords: "CARGANDO...",
            sProcessing: "EN PROCESO...",
            sSearch: "Buscar:",
            sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
            oPaginate: {
                sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
            }
        },
        aaSorting: [
            [0, "desc"]
        ]
    });
</script>