<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <div class="d-flex justify-content-between align-items-center w-100">
            <strong class="text-gray-dark">Busque el documento de interés con el botón buscar</strong>
            <a type="button" class="btn btn-primary" href="javascript:verBuscar();" title="REGISTRAR">Buscar <i class="fa fa-search"></i></a>
        </div>
        <fieldset>
            <legend>Llene los datos</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('idLvmen')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idLvmen')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR ARCHIVO"><i class="fas fa-save"></i> Registrar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->formHidden($form->get('idDocumentosInteres')->setValue(0));
echo $this->form()->closeTag();
?>