<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'GestorPortal';
    switch ($tipo) {
        case 'success':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "new PNotify({
            title: '$titulo',
            text: '$mensaje',
            type: '$tipoToastr',
            styling: 'bootstrap3'
        });";
    }
}
//------------------------------------------------------------------------------

$title = 'Archivos';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#myTable").DataTable({
                    responsive: true,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('js/sistema/normatividad.js'))
    ->prependFile($this->basePath('js/ckeditor.js'))
    ->prependFile($this->basePath('js/jquery.blockUI.js'))
    ->prependFile($this->basePath('js/select2.min.js'))
    ->prependFile($this->basePath('js/select2.es.js'));
?>
<div class="col-md-12 col-sm-12">
    <div class="x_panel">
        <div class="x_title">
            <h2><span data-feather="file-text"></span> Vicerrectoría Académica - Normatividad<small><i><b><i class="fa fa-paw"></i>GestorPortal</small></b></i></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Settings 1</a>
                        <a class="dropdown-item" href="#">Settings 2</a>
                    </div>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <div class="d-flex justify-content-between align-items-center w-100">
                            <strong class="text-gray-dark">Se listan los archivos registrados en el sistema</strong>
                            <a type="button" class="btn btn-primary" href="javascript:verRegistrar();" title="REGISTRAR"><span data-feather="file-plus"></span></a>
                        </div>

                        <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
                            <thead class="thead-dark">
                                <tr>
                                    <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                                    <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
                                    <th scope="col"><i class="fas fa-id-card"></i> NOMBRE</th>
                                    <th scope="col"><i class="fas fa-id-card"></i> TIPO</th>
                                    <th scope="col"><i class="fas fa-id-card"></i> ESTADO</th>
                                    <th scope="col"><i class="fas fa-calendar"></i> REGISTRADO</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($this->fetchAll as $qs) {
                                    $color = '';
                                    $botonPlay = '';
                                    $botonStop = '';
                                    $icono = '';
                                    $title = '';
                                    if ($qs['estado'] == 'Activo') {
                                        $color = 'green';
                                        $botonPlay = 'hidden';
                                        $botonStop = '';
                                    } else {
                                        $color = 'red';
                                        $botonPlay = '';
                                        $botonStop = 'hidden';
                                    }
                                    $ext = explode(".", strrev($qs['archivo']));
                                    if (strrev($ext[0]) == 'zip') {
                                        $icono = 'fa fa-file-archive-o';
                                        $title = 'DESCARGAR ZIP';
                                    } elseif (strrev($ext[0]) == 'pptx') {
                                        $icono = 'fa fa-file-powerpoint-o';
                                        $title = 'DESCARGAR POWERPOINT';
                                    } elseif (strrev($ext[0]) == 'xlsx') {
                                        $icono = 'fa fa-file-excel-o';
                                        $title = 'DESCARGAR EXCEL';
                                    } elseif (strrev($ext[0]) == 'docx') {
                                        $icono = 'fa fa-file-word-o';
                                        $title = 'DESCARGAR WORD';
                                    } else {
                                        $icono = 'fa fa-file-pdf-o';
                                        $title = 'DESCARGAR PDF';
                                    }
                                    echo '<tr>';
                                    echo '<td>' . $qs['idNormatividad']  . '</td>';
                                    echo '<td>';
                                    echo '<a href="javascript:verDetalle(' . $qs['idNormatividad'] . ')" title="VER"><i class="fas fa-eye"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="javascript:verEditar(' . $qs['idNormatividad']  . ')" title="EDITAR"><i class="fa fa-edit"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="javascript:verEliminar(' . $qs['idNormatividad']  . ')" title="ELIMINAR" ' . $botonStop . '><i class="fa fa-trash" style="color:red;"></i></a>';
                                    echo '<a href="javascript:verActivar(' . $qs['idNormatividad']  . ')" title="ACTIVAR" ' . $botonPlay . '><i class="fa fa-recycle" style="color:green;"></i></a>';
                                    echo '&nbsp;&nbsp;';
                                    echo '<a href="./../normatividad/verArchivo/' . $qs['idNormatividad']  . '" target="_blank" title="' . $title . '"><i class="' . $icono . '"></i></a>';
                                    echo '</td>';
                                    echo '<td>' . substr($qs['nombre'], 0, 150)  . '</td>';
                                    echo '<td>' . $qs['tipo']  . '</td>';
                                    echo '<td>' . $qs['estado'] . '</td>';
                                    echo '<td>' . $qs['fechahorareg']  . '</td>';
                                    echo '</tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i> SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>