<div class="modal-body">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Informacion del formulario</legend>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="nombre">Nombre</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['nombre'] . ' ' . $this->form['apellidos']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-address-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="tipoIdentificacion">Tipo de Identificación</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['tipoIdentificacion']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-address-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="identificacion">Identificación</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['identificacion']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-address-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="correo">Correo</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['correo']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-envelope"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="codigo_estudiante">Codigo Estudiante</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['codigo_estudiante'] ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-phone-square"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="programa">Facultad </label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['facultad']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-location-arrow"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="programa">Programa </label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['programa']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-location-arrow"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="periodo_ingreso_universidad">Periodo de Ingreso</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['periodo_ingreso_universidad']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="semestre_actual">Semestre Actual</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['semestre_actual']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="inscrito_por">Inscrito Por</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['inscrito_por']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="inscripcion_psi">Inscripción PSI</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['inscripcion_psi']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-3 col-sm-12">
                    <label class="control-label" for="idForm"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['idForm']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-3 col-sm-12">
                    <label class="control-label" for="id_config">ID Config</label>
                    <div class="input-group">
                        <input type='text' id="id_config" name="id_config" value="<?php echo $this->form['id_config']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-3 col-sm-12">
                    <label class="control-label" for="id_convocatoria">ID Convocatoria</label>
                    <div class="input-group">
                        <input type='text' id="id_convocatoria" name="id_convocatoria" value="<?php echo $this->form['id_convocatoria']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-3 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <input type='text' id="estado" name="estado" value="<?php echo $this->form['estado']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fecha_registro_virtual">Fecha de Registro Virtual</label>
                    <div class="input-group">
                        <input type='text' id="fecha_registro_virtual" name="fecha_registro_virtual" value="<?php echo $this->form['fecha_registro_virtual']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Fecha de Registro</label>
                    <div class="input-group">
                        <input type='text' id="fechahorareg" name="fechahorareg" value="<?php echo $this->form['fechahorareg']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fecha_inscripcion">Fecha de Inscripción</label>
                    <div class="input-group">
                        <input type='text' id="fecha_inscripcion" name="fecha_inscripcion" value="<?php echo $this->form['fecha_inscripcion']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>