<form id="frmRegistrar" action="insertarRecursoRol" method="POST" onsubmit="return validarRegistrar(event, this)">
    <fieldset>
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box table-responsive">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Seleccione los recursos</strong>
                    </div>
                    <table id="myTable4" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
                        <thead class="thead-dark">
                            <tr>
                                <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                                <th data-toggle="tooltip" title="OPCIONES" scope="col"><input type="checkbox" id="checkAll" /> ALL</th>
                                <th scope="col"><i class="fas fa-id-card"></i> RECURSO</th>
                                <th scope="col"><i class="fas fa-id-card"></i> METODO</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->recursos as $rec) {
                                $parte = explode("\\", $rec['recurso']);
                                $parte2 = explode(".", $parte[2]);
                                echo '<tr>';
                                echo '<td>' . $rec['idRecurso'] . '</td>';
                                echo '<td>';
                                echo '<input type="checkbox" value="' . $rec['idRecurso'] . '" name="check_lista[]">';
                                echo '</td>';
                                echo '<td><i style="color: green">' . $parte[0] . '\</i><i style="color: purple">' . $parte[1] . '\</i><i style="color: blue">' . $parte2[0] . '.</i><i>' . $parte2[1] . '</i></td>';
                                echo '<td>' . $rec['metodo'] . '</td>';
                                echo '</tr>';
                            }
                            ?>
                        </tbody>
                    </table>
                    <div hidden>
                        <input id="idRol" name="idRol" value="<?= $this->idRol ?>" class="form-control" readonly>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="form-group">
        <div class="modal-footer" style="padding: 20px">
            <button id="btnRegistrar" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
            <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
        </div>
    </div>
</form>

<script>
    $("#checkAll").change(function() {
        $("input:checkbox").prop('checked', $(this).prop("checked"));
    });
    $("#myTable4").DataTable({
        responsive: true,
        "iDisplayLength": 25,
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
            "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
            "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
            "sInfoEmpty": "Mostrando 0 A 0 registros",
            "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
            "sLoadingRecords": "CARGANDO...",
            "sProcessing": "EN PROCESO...",
            "sSearch": "Buscar:",
            "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
            "oPaginate": {
                "sFirst": "Inicio",
                "sLast": "Fin",
                "sNext": "Siguiente",
                "sPrevious": "Anterior"
            }
        },
        "aaSorting": [
            [0, "desc"]
        ]
    });

    function validarRegistrar(evt, formulario) {
        var idRecurso = '';
        $("input[type=checkbox]:checked").each(function() {
            idRecurso += this.value + ',';
        });
        if (idRecurso === '') {
            Swal.fire("SELECCIONE ALMENOS UN RECURSO", 'GESTORPORTAL', "error");
            return false;
        } else {
            evt.preventDefault();
            Swal.fire({
                title: "&#191;DESEA GUARDAR LA CONFIGURACION DEL PERFIL&#63;",
                text: "",
                icon: "warning",
                showCancelButton: true,
                confirmButtonText: "Si",
                cancelButtonText: "No",
                allowOutsideClick: false
            }).then((result) => {
                if (result.isConfirmed) {
                    formulario.removeAttribute('onsubmit');
                    formulario.submit();
                    bloqueoAjax();
                }
            });
        }
    }
</script>