<div class="modal-body">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Informacion del programa</legend>
            <div class="form-row">
                <div class="form-group col-md-12 col-sm-12">
                    <label class="control-label" for="titulo">Titulo</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['titulo']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <label class="control-label" for="detalle">Contenido</label>
                    <div class="input-group">
                        <textarea id="detalle_programa" name="detalle" class="form-control" rows="10" readonly><?php echo $this->form['detalle']; ?></textarea>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12 text-center">
                    <a href="javascript:verImagen('<?php echo $this->form['imagen']; ?>')" title="VER IMAGEN"><img src="./../../../archivos/podcast_comarca/imagenes/<?php echo $this->form['imagen']; ?>" width="100" height="100" /></a>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="hora_inicio">Autor</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['autor']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="hora_fin">Fecha</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['fecha']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="tipo">Tipo</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['tipo']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="audio_url">Spotify URL</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['audio_url']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-audio-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="audio_id">Spotify ID</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['audio_id']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-audio-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="video_url">YouTube URL</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['video_url']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-film"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label class="control-label" for="video_id">YouTube ID</label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['video_id']  ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-film"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="idPodcastComarca"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <input type='text' value="<?php echo $this->form['idPodcastComarca']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <input type='text' id="estado" name="estado" value="<?php echo $this->form['estado']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <input type='text' id="registradopor" name="registradopor" value="<?php echo $this->form['registradopor']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <input type='text' id="modificadopor" name="modificadopor" value="<?php echo $this->form['modificadopor']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Registrado</label>
                    <div class="input-group">
                        <input type='text' id="fechahorareg" name="fechahorareg" value="<?php echo $this->form['fechahorareg']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahoramod">Modificado</label>
                    <div class="input-group">
                        <input type='text' id="fechahoramod" name="fechahoramod" value="<?php echo $this->form['fechahoramod']; ?>" class="form-control" readonly />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>