<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del evento</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('title')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('title')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('start')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('start')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-check-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('end')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('end')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-times-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('color')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('color')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-paint-brush"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('textColor')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('textColor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-paint-brush"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('allDay')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('allDay')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-reply-all"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="idEvento"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idEvento')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('modificadopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahoramod">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahoramod')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div hidden>
    <input id="idEventoAux" name="idEventoAux" value="<?php echo $this->idEvento; ?>" readonly>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="EDITAR EVENTO"><i class="fas fa-save"></i> Editar</button>
    <button type="button" class="btn btn-danger" title="ELIMINAR EVENTO" onclick="eliminarEvento();"><i class="fa fa-trash"></i> Eliminar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>