<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'GestorPortal';
    switch ($tipo) {
        case 'success':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = '<p><b><i><i class="fa fa-paw"></i> GestorPortal</i></b></p>';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "new PNotify({
            title: '$titulo',
            text: '$mensaje',
            type: '$tipoToastr',
            styling: 'bootstrap3'
        });";
    }
}
//------------------------------------------------------------------------------

$title = 'Eventos';
$this->headTitle($title);
$this->headLink();
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#myTable").DataTable({
                    responsive: true,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('js/sistema/evento.js'))
    ->prependFile($this->basePath('js/jquery.blockUI.js'));

?>
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3><span data-feather="calendar"></span> Solicitudes</h3>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
        <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap table-sm table-hover" cellspacing="0" width="100%">
            <thead class="thead-dark">
                <tr>
                    <th data-toggle="tooltip" title="ID" scope="col"><i class="fa fa-key"></i></th>
                    <th data-toggle="tooltip" title="OPCIONES" scope="col"><i class="fa fa-cog fa-spin fa-lg"></i></th>
                    <th scope="col"><i class="fas fa-id-card"></i> NOMBRE</th>
                    <th scope="col"><i class="fas fa-card"></i> IDENTIFICACION</th>
                    <th scope="col"><i class="fas fa-phone"></i> TELEFONO</th>
                    <th scope="col"><i class="fas fa-envelope"></i> CORREO</th>
                    <th scope="col"><i class="fas fa-calendar"></i> REGISTRADO</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->fetchAll as $qs) {
                    echo '<tr>';
                    echo '<td>' . $qs['idSolicitud']  . '</td>';
                    echo '<td>';
                    echo '<a href="javascript:verEditar(' . $qs['idSolicitud']  . ')" title="EDITAR"><i class="fa fa-edit"></i></a>';
                    echo '</td>';
                    echo '<td>' . $qs['nombre']  . ' ' . $qs['apellido'] . '</td>';
                    echo '<td>' . $qs['identificacion']  . '</td>';
                    echo '<td>' . $qs['telefono'] . '</td>';
                    echo '<td>' . $qs['correo']  . '</td>';
                    echo '<td>' . $qs['fechahorareg']  . '</td>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i> SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var hoy = new Date();
    jQuery(document).ready(function($) {
        $("#calendar").fullCalendar({
            height: 600,
            locale: "es",
            timeZone: "America/Bogota",
            themeSystem: "bootstrap4",
            defaultView: "month",
            weekNumbers: true,
            weekNumbersWithinDays: true,
            nowIndicator: true,
            now: hoy,
            header: {
                left: "prev,next,today",
                center: "title",
                right: "month,basickWeek,basickDay,agendaWeek,agendaDay,listMonth"
            },
            events: [
                <?php
                foreach ($this->fetchAll as $qs) {
                    echo '{';
                    echo 'idSolicitud: "' . $qs['idSolicitud'] .
                        '",';
                    echo 'title: "' . $qs['title'] .
                        '",';
                    echo 'descripcion: "' . $qs['descripcion'] .
                        '",';
                    if ($qs['allDay'] == 'true') {
                        $start = explode(" ", $qs['start']);
                        $end = explode(" ", $qs['end']);
                        echo 'start: "' . $start[0] .
                            '",';
                        echo 'end: "' . $end[0] .
                            '",';
                    } else {
                        echo 'start: "' . $qs['start'] .
                            '",';
                        echo 'end: "' . $qs['end'] .
                            '",';
                    }
                    echo 'color: "' . $qs['color'] .
                        '",';
                    echo 'textColor: "' . $qs['textColor'] .
                        '",';
                    echo '},';
                }
                ?>
            ],
            dayClick: function(event, jsEvent, view) {
                verRegistrar(event);
            },
            eventClick: function(event, jsEvent, view) {
                verEditar(event.idSolicitud);
                $(this).css("border-color", "#ff000a");
            },
            editable: true,
            eventDrop: function(event, delta, revertFunc) {
                moverEvento(event);
            },
            editable: true,
            eventResize: function(event, delta, revertFunc) {
                redimensionar(event);
            },
            navLinks: true,
        })
    });
</script>';