<?php
$form->prepare();
$form->get('archivo')->setAttribute('readonly', true);
$form->get('archivo')->setAttribute('required', false);
$form->get('archivo')->setAttribute('type', 'text');
$form->get('dirigido')->setAttribute('required', false);
$form->get('formato')->setAttribute('required', false);
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Edite los datos</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('tipo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divTipoInforme" style="display: none;">
                    <?= $this->formLabel($form->get('tipoInforme')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipoInforme')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divTipoFecha" style="display: none;">
                    <?= $this->formLabel($form->get('tipoFecha')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipoFecha')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divFecha" style="display: none;">
                    <?= $this->formLabel($form->get('fecha')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fecha')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divDirigido" style="display: none;">
                    <?= $this->formLabel($form->get('dirigido')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('dirigido')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divFormato" style="display: none;">
                    <?= $this->formLabel($form->get('formato')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('formato')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('publicacion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('publicacion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('archivo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('archivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group">
                                <button type="button" onclick="actualizarArchivo()" class="btn btn-primary" title="ACTUALIZAR EL ARCHIVO"><i class="fa fa-upload"></i></button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="idRectoria"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idRectoria')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('modificadopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahoramod">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahoramod')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div hidden>
    <input id="idEventoAux" name="idEventoAux" value="<?php echo $this->idEvento; ?>" readonly>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-success" title="EDITAR PROGRAMA"><i class="fas fa-save"></i> Editar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>

<script>
    $(document).ready(function() {
        if ($('#tipo').val() == 'Auditoría') {
            $("#divTipoInforme").show('slow');
            $("#divTipoFecha").hide("slow");
            $("#divFecha").hide("slow");
            $("#divDirigido").hide("slow");
            $("#divFormato").hide("slow");
            //-------------------------------------
            $('#tipoInforme').attr('required', true);
            $('#tipoFecha').attr('required', false);
            $('#fecha').attr('required', false);
            $('#dirigido').attr('required', false);
            $('#formato').attr('required', false);
        } else if ($('#tipo').val() == 'Interno') {
            $("#divTipoInforme").hide("slow");
            $("#divTipoFecha").show("slow");
            $("#divFecha").show("slow");
            $("#divDirigido").hide("slow");
            $("#divFormato").hide("slow");
            //-------------------------------------
            $('#tipoInforme').attr('required', false);
            $('#tipoFecha').attr('required', true);
            $('#fecha').attr('required', true);
            $('#dirigido').attr('required', false);
            $('#formato').attr('required', false);
        } else if ($('#tipo').val() == 'Externo') {
            $("#divTipoInforme").hide("slow");
            $("#divTipoFecha").show("slow");
            $("#divFecha").show("slow");
            $("#divDirigido").show("slow");
            $("#divFormato").show("slow");
            //-------------------------------------
            $('#tipoInforme').attr('required', false);
            $('#tipoFecha').attr('required', true);
            $('#fecha').attr('required', true);
            $('#dirigido').attr('required', true);
            $('#formato').attr('required', true);
        } else {
            $("#divTipoInforme").hide("slow");
            $("#divTipoFecha").hide("slow");
            $("#divFecha").hide("slow");
            $("#divDirigido").hide("slow");
            $("#divFormato").hide("slow");
            //-------------------------------------
            $('#tipoInforme').attr('required', false);
            $('#tipoFecha').attr('required', false);
            $('#fecha').attr('required', false);
            $('#dirigido').attr('required', false);
            $('#formato').attr('required', false);
        }
    });
</script>