<?php
$form->prepare();
$form->get('archivo')->setAttribute('readonly', true);
$form->get('archivo')->setAttribute('type', 'text');
$form->get('tipo')->setAttribute('readonly', true);
$form->get('tipo')->setAttribute('type', 'text');
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid">
        <fieldset>
            <legend>Llene los datos del evento</legend>
            <div class="row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('nombre')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('nombre')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($form->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('publicacion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('publicacion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('tipo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('tipo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6 col-sm-12" id="divInicioConvocatoria">
                    <?= $this->formLabel($form->get('inicioConvocatoria')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('inicioConvocatoria')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12" id="divFinConvocatoria">
                    <?= $this->formLabel($form->get('finConvocatoria')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('finConvocatoria')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-text-width"></i>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-6 col-sm-12" id="divResolucion">
                    <?= $this->formLabel($form->get('idResolucion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idResolucion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-commenting-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($form->get('archivo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('archivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-pdf-o"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informacion del registro</legend>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="idArchivo"><i class="fa fa-key"></i></label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('idArchivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="estado">Estado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="registradopor">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="modificadopor">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('modificadopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahorareg">Registrado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-12">
                    <label class="control-label" for="fechahoramod">Modificado</label>
                    <div class="input-group">
                        <?= $this->formElement($form->get('fechahoramod')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer" style="padding: 20px">
    <button type="submit" class="btn btn-danger" title="ELIMINAR ARCHIVO"><i class="fa fa-trash"></i> Eliminar</button>
    <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?php
echo $this->form()->closeTag();
?>

<script>
    $(document).ready(function() {
        $('#dependencias').select2({
            allowClear: true,
            search: true,
        });
        $('#dependencias').prop('disabled', true);
    });
</script>